# Generated by Django 5.0.2 on 2024-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_btc_ammount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ammount', models.FloatField(null=True)),
            ],
        ),
    ]
